import "./globals.css";
import type {Metadata} from "next";
import localFont from 'next/font/local';
import { authOptions } from "./api/auth/authOptions";
import {SessionProviderClient} from "./providers/SessionProviderClient";
import {getServerSession} from "next-auth/next";
import Link from 'next/link';
import { useSession } from 'next-auth/react';
import AdminNav from './components/AdminNav';

// Define your local Geist Sans font
const geistSans = localFont({
    // CORRECTED PATH: Go up one directory (from app to src) then into fonts
    src: '../fonts/Geist-Regular.woff2',
    variable: '--font-geist-sans',
    display: 'swap',
});

// Define your local Geist Mono font
const geistMono = localFont({
    // CORRECTED PATH: Go up one directory (from app to src) then into fonts
    src: '../fonts/GeistMono-Regular.woff2',
    variable: '--font-geist-mono',
    display: 'swap',
});


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                             children,
                                         }: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await getServerSession(authOptions);

    return (
        <html lang="en">
        <body className={`${geistSans.className} ${geistMono.className}`}>
        <SessionProviderClient session={session}>
            {/*<AdminNav />*/}
            {children}
        </SessionProviderClient>
        </body>
        </html>
    );
}